name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      env:
        secret: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        pwd
        ls -lh >> 1.txt
        cat 1.txt
        # docker build . --file Dockerfile --tag wzhy1234/ffmpeg-qsv:latest
        # docker login -u wzhy1234 -p $secret
        # docker push wzhy1234/ffmpeg-qsv:latest
