name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        secret: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        docker build . --file Dockerfile --tag wzhy1234/ffmpeg-vaapi:latest
        docker login -u wzhy1234 -p $secret
        docker push wzhy1234/ffmpeg-vaapi:latest
